{{- if .Values.backup.enabled -}}
{{- include "nebari-longhorn-backup.validate" . -}}
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: {{ include "nebari-longhorn-backup.targetGroup" . }}-daily-backup
  namespace: {{ .Values.longhornNamespace }}
  labels:
    {{- include "nebari-longhorn-backup.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  name: {{ include "nebari-longhorn-backup.targetGroup" . }}-daily-backup
  cron: {{ .Values.backup.cron | quote }}
  task: backup
  groups:
    - {{ include "nebari-longhorn-backup.targetGroup" . }}
  retain: {{ .Values.backup.retain }}
  concurrency: {{ .Values.backup.concurrency }}
{{- end }}
