{{- if .Values.snapshot.enabled -}}
{{- include "nebari-longhorn-backup.validate" . -}}
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-hourly-snapshot
  namespace: {{ .Values.longhornNamespace }}
  labels:
    {{- include "nebari-longhorn-backup.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  name: default-hourly-snapshot
  cron: {{ .Values.snapshot.cron | quote }}
  task: snapshot
  groups:
    - default
  retain: {{ .Values.snapshot.retain }}
  concurrency: {{ .Values.snapshot.concurrency }}
{{- end }}
