{{- if .Values.storageClass.enabled }}
{{- include "nebari-longhorn-backup.validate" . -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "nebari-longhorn-backup.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: {{ .Values.storageClass.numberOfReplicas | quote }}
  staleReplicaTimeout: "30"
  fsType: {{ .Values.storageClass.fsType | quote }}
  recurringJobSelector: |
    [{"name":{{ include "nebari-longhorn-backup.targetGroup" . | quote }},"isGroup":true}]
{{- end }}
